site_name: Cloud Masking - Qgis plugin
site_description: Cloud masking for Landsat (4, 5, 7 and 8) products using different process such as Fmask, Blue Band, Cloud QA and Pixel QA.
site_author: Xavier Corredor Llano, SMByC-IDEAM
site_favicon: img/favicon.png
site_url: https://smbyc.bitbucket.io/qgisplugins/cloudmasking
repo_url: https://github.com/SMByC/CloudMasking
theme:
  name: mkdocs
extra_css:
    - css/extra.css
markdown_extensions:
  - smarty
  - admonition
  - toc:
      permalink: true
  - sane_lists
nav:
  - Home: index.md
  - Installation: installation.md
  - How to use: how_to_use.md
  - Cloud Filters: cloud_filters.md
